default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: d3nip374udq6gm
  username: qcdqehtbytnekt
  password: 6f3jmpNwGnTmh8zijyvm64PBS9
  host: ec2-23-21-234-218.compute-1.amazonaws.com
  port: 5432

test:
  <<: *default
  database: dashboard_test

production:
  <<: *default
  #database: carezapp_production
  #username: carezapp
  #password: ppazerac
  #host: carezapp-production.c0sqj89scu7r.eu-west-1.rds.amazonaws.com
  #port: 5432
  database: d3nip374udq6gm
  username: qcdqehtbytnekt
  password: 6f3jmpNwGnTmh8zijyvm64PBS9
  host: ec2-23-21-234-218.compute-1.amazonaws.com
  port: 5432